### ISSUE TITLE
提一个关于离线版的建议

### ISSUE THREAD

**Issue by Young-Lord** [yuzh2001/bamboo-debate-timer#1]
我们学校的辩论赛使用需求大概是这样的：在PPT里插入程序超链接，使用时直接点超链接就可以进入计时，但目前辩题、队名、设置等仍需要手动输入。同时，每个号码需要单独生成。对此，个人想法有以下两条：
1. 对于计时器信息直接以单独 JSON 文件存储，并通过 Node.JS 读取文件直接加载；
2. 配置信息同上 支持以单独文件存储
3. 允许通过命令行参数指定计时器文件路径以及配置文件路径

最后，感谢您无私奉献这样一个优质工具！（以及是否应该在官网放个 GitHub repo 链接？）

**Comment by pkmq24** [comment]
比较建议的用法是，先提前打开计时器，然后ppt直接alt+tab切换过去就好。其他方法都有点复杂且难以配置

**Comment by pkmq24** [comment]
还有个情况是，这个repo已经很久没更新了，我发现大家对开源这件事情的热情不是很高hhh你如果有兴趣参与开发可以微信加我私聊~vx(yuzhuohao)

**Comment by Young-Lord** [comment]
开发的话由于最近要用到所以自己魔改了一下，代码位于 https://github.com/sdgh-net/bamboo-debate-timer
而且这样其实有个问题：Electron不能多实例运行，所以像我们这边一次连续进行几场的就难搞了
以及，你这代码能写点注释吗……

**Comment by Young-Lord** [comment]
毕竟网站上甚至没有一个开源地址的链接，想有热情还得找好一会

**Comment by pkmq24** [comment]
1.曾经挂过 挂了一年吧也没几个人看，后面就懒得挂了。也出于对商业机构的不信任，不愿意再持续更新开源版本了。
2.你要是有兴趣，可以找机会聊聊，加入进来一起开发闭源的目前线上版本(https://bian.cool  )，很多设计和逻辑都改变了
3.不写注释 嗯 历史遗留问题吧。考虑到近三年都是我自己一个人开发，就没啥动力写注释。

**Comment by pkmq24** [comment]
辛苦啦 看了一下你的fork 受累了读无注释代码hhh写的很棒 祝好
